# Prayer-clause → Scripture map for the bloodline repentance study.
# Clause text follows Core / Round 1 / Round 2 / Round 3 templates.

CLAUSES = [
    {
        "id": "spoken",
        "clause": "These prayers are to be spoken, not simply read silently.",
        "rounds": "All rounds",
        "why": "Bloodline repentance is confession. A record is answered with the mouth, not only with private agreement.",
        "refs": [
            ("Rom 10:9-10", "Believe in the heart and confess with the mouth."),
            ("Prov 28:13", "He who covers sins does not prosper; confession and forsaking find mercy."),
            ("Lev 5:5", "When guilty, confess the sin."),
            ("Lev 26:40", "Confess iniquity and the iniquity of the fathers."),
            ("Josh 7:19", "Give glory to God and make confession."),
            ("Ps 32:5", "I acknowledged my sin; You forgave."),
            ("Ps 51:3-4", "My sin is ever before me; against You I have sinned."),
            ("Dan 9:4-5", "Daniel prayed and made confession with his mouth."),
            ("Neh 1:6-7", "Confess the sins of the children of Israel."),
            ("Matt 10:32", "Confess Christ before men."),
            ("1 John 1:9", "If we confess our sins, He is faithful and just to forgive."),
            ("Rev 12:11", "They overcame by the blood and by the word of their testimony."),
        ],
    },
    {
        "id": "on-behalf",
        "clause": "On behalf of the (2nd–5th / 6th–20th) generation… I agree WE are guilty.",
        "rounds": "Round 2 and Round 3 (Round 1 speaks I, then lays both sides back to Adam)",
        "why": "God receives representative confession. A living voice may agree with guilt the line carried, without pretending the dead can be forced to believe.",
        "refs": [
            ("Lev 26:40-42", "Confess the iniquity of the fathers; then God remembers the covenant."),
            ("Ex 20:5-6", "Iniquity visited; mercy to thousands who love Him."),
            ("Ex 34:6-7", "Forgiving iniquity, transgression, and sin; visiting iniquity of fathers."),
            ("Num 14:18-19", "Moses pleads the same character of God over a whole people."),
            ("Deut 29:14-15", "Covenant with him who stands here and with him who is not here."),
            ("Josh 7:1, 10-26", "Achan's house bears a corporate record until it is judged."),
            ("2 Sam 21:1-14", "Saul's bloodguilt sits on the land until it is answered."),
            ("Ezra 9:6-15", "Ezra confesses WE; our iniquities, our fathers."),
            ("Ezra 10:1-4", "A remnant acts for the congregation."),
            ("Neh 1:6-9", "I and my father's house have sinned."),
            ("Neh 9:2-3, 33-38", "Seed of Israel confess iniquities of their fathers."),
            ("Dan 9:5-19", "We have sinned; our fathers; the whole people named."),
            ("Jer 14:20", "We acknowledge our wickedness and the iniquity of our fathers."),
            ("Ps 106:6", "We have sinned with our fathers."),
            ("Lam 5:7, 16", "Fathers sinned; we bear; the crown is fallen; we have sinned."),
            ("Acts 2:38-39", "The promise is to you, your children, and all afar off."),
            ("Rom 5:12-19", "One man, many made sinners; one Man, many made righteous."),
        ],
    },
    {
        "id": "preferred",
        "clause": "I agree that WE made it more important than God, loved it more than God, and preferred it instead of God.",
        "rounds": "All rounds",
        "why": "That is the Bible's definition of idolatry. The prayer names the topic as a rival god, not a personality quirk.",
        "refs": [
            ("Ex 20:3-5", "No other gods; no graven image; do not bow or serve."),
            ("Deut 6:4-5", "Love the LORD with all heart, soul, and might."),
            ("Deut 8:19", "If you go after other gods, you perish."),
            ("Josh 24:14-24", "Choose whom you will serve; put away foreign gods."),
            ("1 Sam 15:23", "Rebellion is as witchcraft; stubbornness as idolatry."),
            ("1 Kgs 18:21", "How long halt between two opinions?"),
            ("Ps 16:4", "Sorrow multiplied who hasten after another god."),
            ("Isa 42:8", "My glory I will not give to another."),
            ("Jer 2:13", "Two evils: forsaken the fountain; hewn broken cisterns."),
            ("Ezek 14:3-7", "Idols in the heart; God answers according to the idol."),
            ("Hos 4:12", "Spirit of whoredoms causes them to err."),
            ("Matt 6:24", "No one can serve two masters."),
            ("Matt 22:37", "First commandment: love God with all."),
            ("Luke 14:26-33", "Hate even father, mother, life — compared with Christ."),
            ("Rom 1:21-25", "Worshiped the creature more than the Creator."),
            ("Col 3:5", "Covetousness is idolatry."),
            ("Jas 4:4", "Friendship with the world is enmity with God."),
            ("1 John 5:21", "Keep yourselves from idols."),
        ],
    },
    {
        "id": "idolatry-altar",
        "clause": "For this idolatry, adultery, and rebellion, I lay my life / my bloodline on the altar of God.",
        "rounds": "All rounds (Round 2 names the bloodline on the altar)",
        "why": "Spiritual unfaithfulness is adultery. Rebellion is witchcraft. The altar is where a life or a line is given back to God instead of to the rival master.",
        "refs": [
            ("Gen 22:9-18", "Abraham lays Isaac on the altar; the seed is blessed."),
            ("Ex 20:24-26", "Altar of the LORD; His name remembered."),
            ("Ex 32:1-8", "Idolatry as a feast that breaks covenant."),
            ("Lev 1:3-9", "Burnt offering wholly given."),
            ("Deut 12:2-7", "Destroy rival altars; bring offerings to His place."),
            ("1 Kgs 18:30-39", "Repair the altar of the LORD; fire answers."),
            ("Ps 51:17-19", "Broken spirit; then God is pleased with sacrifices."),
            ("Isa 6:6-7", "Coal from the altar touches the mouth."),
            ("Jer 3:1-14", "Treacherous wife; return, for I am married to you."),
            ("Ezek 16:15-32", "Jerusalem's adultery with idols."),
            ("Hos 1:2; 2:2-7; 3:1", "Whoredom from the LORD; buy her back."),
            ("Hos 14:1-2", "Return; take away iniquity; receive us graciously."),
            ("Matt 5:23-24", "Leave the gift at the altar; be reconciled."),
            ("Rom 6:13", "Yield yourselves to God as those alive from the dead."),
            ("Rom 12:1", "Present your bodies a living sacrifice."),
            ("1 Cor 10:20-22", "Fellowship with demons vs the Lord's table; jealousy of God."),
            ("Jas 4:4-8", "Adulterers; submit, resist, draw near."),
            ("Heb 13:10-15", "We have an altar; offer praise and doing good."),
        ],
    },
    {
        "id": "covenants-records",
        "clause": "I recognize that this is happening because of agreements, blood covenants, blood contracts, hexes, vexes, interaction with the blood, and satanic ritual agreements… because of [fruit] with the parent [Principality].",
        "rounds": "All rounds",
        "why": "Scripture treats covenants, blood, and spiritual rulers as legal. A copied master is not only a habit; it is often a claim.",
        "refs": [
            ("Gen 15:8-18", "Blood pieces; God cuts covenant."),
            ("Ex 24:3-8", "Blood of the covenant on the people."),
            ("Lev 17:11", "Life of the flesh is in the blood; atonement."),
            ("Deut 29:12-21", "Enter covenant and oath; a root bearing gall if they turn."),
            ("Isa 28:14-18", "Covenant with death disannulled; agreement with hell shall not stand."),
            ("Isa 49:24-26", "Lawful captive; prey of the mighty taken; children saved."),
            ("Jer 31:31-34", "New covenant; law in the heart; iniquity remembered no more."),
            ("Dan 10:12-13, 20-21", "Princes of Persia and Greece withstand; Michael helps."),
            ("Matt 12:29", "Bind the strong man; spoil his goods."),
            ("Luke 11:21-22", "Stronger than the strong man takes the armor."),
            ("John 8:34", "Whoever commits sin is the servant of sin."),
            ("Acts 19:18-19", "Confess deeds; burn curious arts books."),
            ("Rom 6:16", "To whom you yield, his servants you are."),
            ("1 Cor 10:16-21", "Cup of blessing vs cup of demons."),
            ("Gal 4:3, 8-9", "Bondage under elements; turn again to weak and beggarly."),
            ("Eph 2:1-3", "Walked according to the prince of the power of the air."),
            ("Eph 6:12", "Wrestle not against flesh and blood, but principalities."),
            ("Col 2:13-15", "Handwriting of ordinances blotted out; principalities spoiled."),
            ("Heb 2:14-15", "Destroy him that had the power of death; deliver from bondage."),
            ("Rev 12:9-11", "Dragon, accuser; overcome by the blood."),
        ],
    },
    {
        "id": "lay-generations",
        "clause": "For the accusation of this record, I lay down the 2nd–5th / 6th–20th generations (Round 1: mother's side, father's side, all the way back to Adam).",
        "rounds": "All rounds",
        "why": "The accusation is against a record in a line. Torah already names visitation to the third and fourth, and mercy far beyond that. The prayers go to Adam because that is where the first record entered the race.",
        "refs": [
            ("Gen 3:15-19", "The first record: seed, pain, ground, death."),
            ("Gen 5:1-3", "Adam begets in his own likeness after the fall."),
            ("Ex 20:5", "Visiting iniquity to the third and fourth generation."),
            ("Ex 34:7", "Third and fourth; also keeping mercy for thousands."),
            ("Num 14:18, 31-33", "Visitation; children bear the wilderness years."),
            ("Deut 5:9-10", "Same third/fourth and thousands pattern."),
            ("Deut 7:9", "Mercy to a thousand generations of them that love Him."),
            ("1 Kgs 21:21-29", "Judgment on Ahab's house delayed to his son's days."),
            ("2 Kgs 10:30", "Jehu's children to the fourth generation on the throne."),
            ("2 Kgs 5:27", "Gehazi's leprosy cleaves to his seed forever."),
            ("Neh 9:2", "Seed of Israel confess."),
            ("Ps 79:8", "Remember not against us former iniquities."),
            ("Ps 109:14", "Let the iniquity of his fathers be remembered."),
            ("Isa 14:21", "Prepare slaughter for children for the iniquity of their fathers."),
            ("Jer 32:18", "Recompensest the iniquity of the fathers into the bosom of their children."),
            ("Lam 5:7", "Our fathers have sinned… we have borne their iniquities."),
            ("Ezek 18:1-20", "Sour grapes proverb corrected — the living soul must repent."),
            ("Luke 3:23-38", "Genealogy of Jesus back to Adam."),
            ("Rom 5:12-21", "By one man sin entered; by One Man grace."),
            ("1 Cor 15:21-22, 45-49", "In Adam all die; in Christ all made alive."),
            ("Heb 7:9-10", "Levi paid tithes in Abraham — a line present in the ancestor."),
        ],
    },
    {
        "id": "no-blame",
        "clause": "I refuse to blame anyone anymore… I take accountability for what my bloodline copied… AND FORGIVE everyone who taught us.",
        "rounds": "All rounds",
        "why": "Blame keeps the record open. Accountability and forgiveness close it. The living generation answers for what it copied, without making the teachers into an excuse.",
        "refs": [
            ("Gen 3:12-13", "Adam blames Eve; Eve blames the serpent — the first retained record."),
            ("Ezek 18:20", "The soul that sinneth, it shall die; son shall not bear the father's guilt as a substitute for his own repentance."),
            ("Prov 28:13", "Cover vs confess and forsake."),
            ("Lam 3:39-41", "Why complain? Let us search and turn."),
            ("Matt 7:1-5", "First the beam in your own eye."),
            ("Luke 6:37", "Forgive, and you shall be forgiven."),
            ("John 8:7-11", "Without sin among you; go and sin no more."),
            ("Rom 2:1-6", "Judging another, you condemn yourself."),
            ("Rom 14:12", "Every one shall give account of himself to God."),
            ("Gal 6:4-5", "Prove his own work; each bear his own burden."),
            ("Eph 4:31-32", "Put away bitterness; forgive as God for Christ's sake forgave."),
            ("Col 3:13", "Forgiving one another; as Christ forgave you."),
            ("Jas 4:11", "Speak not evil of one another."),
            ("1 Pet 2:23-24", "He committed Himself to Him that judges righteously."),
        ],
    },
    {
        "id": "unknown-repentance",
        "clause": "If people from other bloodlines have repented and we don't know about it, I STILL… forgive every way we remembered people the way Jesus doesn't.",
        "rounds": "Round 2 / Round 3 (Round 1: 'If they have repented and I don't know about it')",
        "why": "You will not retain a case by ignorance. Jesus does not keep a memory as an accusation once the Father has received repentance.",
        "refs": [
            ("1 Sam 16:7", "Man looks on the outward; the LORD looks on the heart."),
            ("Isa 43:25", "I, even I, blot out transgressions and will not remember."),
            ("Jer 31:34", "I will remember their sin no more."),
            ("Mic 7:18-19", "He does not retain His anger; casts sins into the sea."),
            ("Matt 6:14-15", "If you forgive, your Father will forgive."),
            ("Matt 18:21-35", "Forgive from the heart; the unforgiving servant is retained."),
            ("Mark 11:25", "When you stand praying, forgive — if you have ought against any."),
            ("Luke 17:3-4", "If he repent, forgive; seven times in a day."),
            ("Luke 23:34", "Father, forgive them; they know not what they do."),
            ("John 20:23", "Whose soever sins ye remit, they are remitted; whose ye retain, they are retained."),
            ("1 Cor 13:5", "Love thinks no evil."),
            ("2 Cor 5:16", "Know no man after the flesh."),
            ("Phil 3:13", "Forgetting those things which are behind."),
            ("1 Pet 4:8", "Love covers a multitude of sins."),
        ],
    },
    {
        "id": "vain-imaginations",
        "clause": "Representing my bloodline, I forgive them for not capturing every vain imagination and bringing it to Jesus as given in 2 Corinthians 10:3-5.",
        "rounds": "Round 3 (explicit); implied in Round 1–2 memory work",
        "why": "Copied masters live in thought-suggestions. The bloodline's failure to take thoughts captive is itself confessed and forgiven.",
        "refs": [
            ("Gen 6:5", "Every imagination of the thoughts of the heart only evil."),
            ("Gen 8:21", "Imagination of man's heart is evil from his youth."),
            ("Ps 19:14", "Let the words of my mouth and the meditation of my heart be acceptable."),
            ("Ps 139:23-24", "Search me; know my thoughts."),
            ("Prov 4:23", "Keep the heart with all diligence."),
            ("Prov 23:7", "As he thinks in his heart, so is he."),
            ("Isa 26:3", "Whose mind is stayed on You."),
            ("Isa 55:7", "Let the unrighteous man forsake his thoughts."),
            ("Jer 4:14", "Wash your heart from wickedness; vain thoughts."),
            ("Matt 5:28", "Look and lust already committed in the heart."),
            ("Matt 15:19", "Out of the heart proceed evil thoughts."),
            ("Rom 1:21", "Became vain in their imaginations."),
            ("Rom 8:5-7", "Mind of the flesh vs mind of the Spirit."),
            ("Rom 12:2", "Be transformed by the renewing of your mind."),
            ("2 Cor 10:3-5", "Casting down imaginations; every thought captive to Christ."),
            ("Eph 4:17-23", "Futility of mind; be renewed in the spirit of your mind."),
            ("Phil 4:8", "Think on these things."),
            ("Col 3:2", "Set your affection on things above."),
            ("Heb 4:12", "Word of God discerns thoughts and intents."),
        ],
    },
    {
        "id": "not-people",
        "clause": "…and not warring against people as given in Ephesians 6:12.",
        "rounds": "Round 3 (explicit)",
        "why": "Bloodline repentance wars against principalities and records, not against the people who taught the habit.",
        "refs": [
            ("Gen 32:24-28", "Jacob wrestles with God, not Esau."),
            ("1 Sam 17:45-47", "The battle is the LORD's."),
            ("2 Chr 20:15", "The battle is not yours, but God's."),
            ("Ps 35:1", "Plead my cause against them that strive with me."),
            ("Isa 49:25", "I will contend with him that contendeth with you."),
            ("Zech 3:1-2", "The LORD rebuke you, O Satan — not Joshua."),
            ("Matt 5:44", "Love your enemies; pray for them."),
            ("Matt 16:23", "Get behind Me, Satan — spoken to a man being used."),
            ("John 10:10", "The thief comes to steal; Christ comes to give life."),
            ("Rom 12:19-21", "Vengeance is Mine; overcome evil with good."),
            ("2 Cor 10:3-4", "We do not war after the flesh; weapons are mighty through God."),
            ("Eph 6:10-18", "Armor of God; wrestle not against flesh and blood."),
            ("Col 2:15", "He spoiled principalities and made a show of them."),
            ("1 Pet 5:8-9", "Adversary the devil; resist steadfast in the faith."),
            ("Rev 12:7-11", "War in heaven; they overcame him."),
        ],
    },
    {
        "id": "forgive-then-ask",
        "clause": "I ask You Father to forgive my bloodline since I have forgiven other bloodlines. I ask You to judge between me and them so that the judgment is pure and holy.",
        "rounds": "All rounds (Round 1: forgive me since I have forgiven others)",
        "why": "Remission on earth is tied to remission received. Then the Father, not the intercessor, judges between lines so the case is clean.",
        "refs": [
            ("Gen 16:5", "The LORD judge between me and thee."),
            ("Gen 31:53", "The God of Abraham judge between us."),
            ("1 Sam 24:12, 15", "The LORD judge between me and thee."),
            ("1 Sam 26:23", "The LORD render to every man his righteousness."),
            ("2 Chr 19:6-7", "You judge not for man, but for the LORD; no iniquity with the LORD."),
            ("Ps 7:8-9", "Judge me, O LORD; let wickedness of the wicked come to an end."),
            ("Ps 82:1-8", "God stands in the congregation of the mighty; judge righteously."),
            ("Isa 11:3-4", "He shall not judge after the sight of his eyes."),
            ("Matt 6:12, 14-15", "Forgive us as we forgive; if you forgive…"),
            ("Matt 7:2", "With what judgment you judge, you shall be judged."),
            ("Matt 18:18", "Bind and loose on earth and in heaven."),
            ("Mark 11:25-26", "Forgive, that your Father may forgive."),
            ("Luke 6:36-37", "Be merciful; forgive and you shall be forgiven."),
            ("John 20:21-23", "As the Father sent Me; receive the Holy Ghost; remit or retain."),
            ("Acts 2:38", "Repent… for the remission of sins."),
            ("Rom 2:5-6", "Righteous judgment of God; according to deeds."),
            ("Jas 2:13", "Mercy rejoices against judgment."),
            ("1 Pet 1:17", "The Father judges without respect of persons."),
        ],
    },
    {
        "id": "stop-serving",
        "clause": "I no longer want to serve [topic] or [fruit]. I am asking for the forgiveness of God on this and for the Blood of Jesus to cover the record and speak instead.",
        "rounds": "All rounds",
        "why": "A master is changed. The Blood does not merely comfort; it covers the accusation and speaks a better word than the record.",
        "refs": [
            ("Ex 12:7, 13", "Blood on the door; when I see the blood, I pass over."),
            ("Lev 17:11", "Blood makes atonement."),
            ("Isa 1:18", "Though sins be as scarlet, they shall be white as snow."),
            ("Isa 43:25", "I blot out thy transgressions."),
            ("Zech 3:3-5", "Filthy garments removed; change of raiment."),
            ("Zech 13:1", "Fountain opened for sin and uncleanness."),
            ("Matt 26:28", "Blood of the new testament for the remission of sins."),
            ("John 1:29", "Lamb of God who takes away the sin of the world."),
            ("Rom 3:24-25", "Redemption; propitiation through faith in His blood."),
            ("Rom 6:6-18", "Old man crucified; no longer servants of sin; servants of righteousness."),
            ("Eph 1:7", "Redemption through His blood, the forgiveness of sins."),
            ("Col 1:14, 20", "Forgiveness; peace through the blood of His cross."),
            ("Col 2:14", "Blotting out the handwriting of ordinances that was against us."),
            ("Heb 9:12-14, 22", "His own blood; purge conscience; without shedding of blood no remission."),
            ("Heb 10:16-22", "Sins remembered no more; enter by the blood."),
            ("Heb 12:24", "Blood of sprinkling that speaks better things than that of Abel."),
            ("1 Pet 1:18-19", "Redeemed with the precious blood of Christ."),
            ("1 John 1:7-9", "Blood of Jesus Christ cleanses from all sin."),
            ("Rev 1:5", "Washed us from our sins in His own blood."),
            ("Rev 12:11", "Overcame him by the blood of the Lamb."),
        ],
    },
    {
        "id": "divorce-record",
        "clause": "I also ask for a spiritual decree of divorce from this record. We don't have room in my bloodline for unconfessed records.",
        "rounds": "All rounds",
        "why": "A covenant with death, an agreement with a master, is cut. Unconfessed records are retained sins; they keep the captivity lawful.",
        "refs": [
            ("Deut 24:1-4", "Bill of divorcement as a legal cut — imagery for putting away."),
            ("Isa 28:18", "Your covenant with death shall be disannulled."),
            ("Isa 50:1", "Where is the bill of your mother's divorcement?"),
            ("Jer 3:8", "I had put her away and given her a bill of divorce."),
            ("Hos 2:2", "She is not My wife, neither am I her husband — then restoration."),
            ("Ezra 10:3-12", "Make a covenant to put away; the congregation answers."),
            ("Prov 28:13", "He that covers his sins shall not prosper."),
            ("Ps 32:1-5", "Blessed is he whose transgression is forgiven; I acknowledged."),
            ("John 20:23", "Remit or retain."),
            ("Acts 3:19", "Repent, that sins may be blotted out."),
            ("Rom 7:1-6", "Dead to the law by the body of Christ; married to Another."),
            ("1 Cor 6:15-20", "Shall I take the members of Christ and make them members of a harlot?"),
            ("2 Cor 6:14-18", "Come out; be separate; I will be a Father."),
            ("Eph 5:11", "Have no fellowship with the unfruitful works of darkness."),
            ("Rev 18:4-5", "Come out of her, My people; her sins have reached unto heaven."),
        ],
    },
    {
        "id": "crown",
        "clause": "I cast off of my head the crown of iniquity that had been attached to my head. You are banned from my life, my mind, my heart, and my body.",
        "rounds": "All rounds",
        "why": "Iniquity sat on the head as a claim of rule. Aaron's plate bore iniquity on the forehead until atonement. The prayers refuse that crown and shut the gates of life, mind, heart, and body.",
        "refs": [
            ("Ex 28:36-38", "Holy to the LORD on the forehead; Aaron bears the iniquity of the holy things."),
            ("Lev 8:9", "The holy crown upon the mitre."),
            ("2 Sam 12:30", "Crown taken from a defeated king."),
            ("Ps 7:16", "His mischief shall return upon his own head."),
            ("Ps 21:3", "You set a crown of pure gold on his head — the true crown."),
            ("Ps 103:4", "Who redeemeth thy life; who crowneth thee with lovingkindness."),
            ("Prov 16:31", "Hoary head is a crown of glory if it be found in the way of righteousness."),
            ("Isa 28:1-3", "Woe to the crown of pride."),
            ("Lam 5:16", "The crown is fallen from our head; woe unto us, for we have sinned."),
            ("Ezek 21:25-26", "Remove the diadem; take off the crown."),
            ("Zech 3:4-5", "Filthy garments off; fair mitre upon his head."),
            ("Matt 27:29", "Crown of thorns — the false crown put on Christ."),
            ("Rom 6:12-13", "Let not sin reign in your mortal body."),
            ("Rom 12:1-2", "Bodies a living sacrifice; mind renewed."),
            ("1 Cor 6:19-20", "Body is the temple; glorify God in body and spirit."),
            ("2 Cor 10:5", "Bringing into captivity every thought."),
            ("Eph 4:22-24", "Put off the old man; put on the new."),
            ("1 Pet 5:4", "You shall receive a crown of glory that fades not."),
            ("Rev 3:11", "Hold fast, that no man take thy crown."),
            ("Rev 4:10", "Cast their crowns before the throne."),
        ],
    },
    {
        "id": "no-accusation",
        "clause": "Give me courage to be responsible for every other temptation and accusation… so that he no longer has any more open accusations against me. I thank You for the people You have put in my life to help me walk out a life of repentance, because of walking in discipleship.",
        "rounds": "All rounds",
        "why": "The goal is a closed case, not a one-time feeling. Discipleship is how repentance is walked, not only spoken.",
        "refs": [
            ("Job 1:8-11", "The accuser's first pattern against a righteous man."),
            ("Zech 3:1-5", "Satan at the right hand to accuse; the LORD rebukes; garments changed."),
            ("Luke 9:23", "Take up the cross daily."),
            ("John 8:10-11", "Neither do I condemn you; go and sin no more."),
            ("John 16:8-11", "The Spirit reproves of sin, righteousness, and judgment."),
            ("Acts 2:42", "They continued in the apostles' doctrine, fellowship, breaking of bread, prayers."),
            ("Rom 8:1", "No condemnation to them in Christ Jesus."),
            ("Rom 8:33-34", "Who shall lay anything to the charge of God's elect? It is God that justifies."),
            ("1 Cor 4:15-17", "Fathers in Christ; be followers of me."),
            ("Gal 6:1-2", "Restore; bear one another's burdens."),
            ("Eph 4:11-16", "Apostles, prophets, evangelists, pastors, teachers — for the saints."),
            ("Phil 2:12-13", "Work out your salvation; God works in you."),
            ("Col 1:28", "Warning every man; teaching every man; present every man perfect."),
            ("2 Tim 2:2", "Commit to faithful men who shall teach others also."),
            ("Heb 3:13", "Exhort one another daily, lest any be hardened."),
            ("Heb 10:24-25", "Consider one another; not forsaking the assembling."),
            ("Jas 5:16", "Confess faults one to another; pray one for another."),
            ("1 Pet 5:8-10", "Adversary; resist; God will stablish you."),
            ("Rev 12:10", "The accuser of our brethren is cast down."),
        ],
    },
    {
        "id": "in-jesus-name",
        "clause": "In the name of Jesus, Amen.",
        "rounds": "All rounds",
        "why": "Access, authority, and the close of the case are in His name — not in the bloodline's sincerity.",
        "refs": [
            ("Joel 2:32", "Whosoever shall call on the name of the LORD shall be delivered."),
            ("Matt 18:19-20", "Agree touching anything; gathered in My name."),
            ("Matt 28:18-19", "All authority; baptizing in the name."),
            ("Mark 16:17", "In My name they shall cast out devils."),
            ("Luke 10:17", "Even the devils are subject unto us through Thy name."),
            ("John 14:13-14", "Whatsoever you ask in My name, I will do."),
            ("John 16:23-24", "Ask the Father in My name."),
            ("Acts 3:6, 16", "In the name of Jesus Christ… His name through faith."),
            ("Acts 4:12", "None other name under heaven given among men."),
            ("Acts 19:13-17", "The name is not a charm; Jesus I know."),
            ("Phil 2:9-11", "A name above every name; every knee bows."),
            ("Col 3:17", "Do all in the name of the Lord Jesus."),
            ("Heb 13:15", "Offer the sacrifice of praise… giving thanks to His name."),
        ],
    },
]
