# Canonical catalog: Genesis → Revelation.
# Only passages that underwrite bloodline repentance as the prayers practice it.

CANON = [
    ("Genesis", [
        ("1:26-28", "Image, fruitfulness, dominion — the original commission of a line."),
        ("3:12-19", "Blame, the curse, and the first bloodline record."),
        ("3:15", "Seed of the woman vs seed of the serpent — conflict runs in lines."),
        ("4:8-11", "Abel's blood cries from the ground; a record in the earth."),
        ("4:23-24", "Lamech multiplies violence in Cain's line."),
        ("5:1-3", "Generations of Adam; likeness after the fall."),
        ("6:5-9", "Imagination of the heart; Noah perfect in his generations."),
        ("8:20-21", "Altar after the flood; imagination still evil from youth."),
        ("9:8-17", "Covenant with Noah and his seed after him."),
        ("11:1-9", "Babel: a people united in rebellion."),
        ("12:1-3", "Blessing in Abraham for all families of the earth."),
        ("12:7", "To thy seed will I give this land."),
        ("15:5-18", "Seed as stars; blood pieces; God cuts the covenant."),
        ("17:7-14", "Everlasting covenant with seed; household circumcision."),
        ("17:23-27", "Abraham circumcises his whole house the same day."),
        ("18:17-19", "Abraham will command his children and household after him."),
        ("19:12-29", "A household pulled out; looking back costs a life."),
        ("22:2-18", "Altar, seed, and oath: in thy seed all nations blessed."),
        ("26:3-5, 24", "Isaac inherits because Abraham obeyed."),
        ("27:27-40", "Blessing and consequence travel in a family."),
        ("28:13-15", "I am with thee; to thy seed; I will not leave thee."),
        ("31:53", "God judge between us — the prayer's 'judge between' line."),
        ("32:24-30", "The name change: a man representing a people (Israel)."),
        ("35:2-4", "Put away strange gods in the household; earrings buried."),
        ("49:1-28", "What shall befall the sons in the last days."),
        ("50:15-21", "Joseph remits what the brothers retained as guilt."),
    ]),
    ("Exodus", [
        ("1:1-7", "The sons of Israel named as a people."),
        ("3:6, 15", "God of Abraham, Isaac, and Jacob — the God of a line."),
        ("4:22-23", "Israel is My son, even My firstborn."),
        ("12:3-13", "A lamb for a house; blood on the door; the destroyer passes."),
        ("12:21-27", "When your children ask, you shall say: it is the sacrifice of the LORD's passover."),
        ("13:8-14", "Tell thy son; the firstborn is the LORD's."),
        ("19:5-6", "A kingdom of priests, a holy nation."),
        ("20:3-6", "No other gods; visiting iniquity to the third and fourth; mercy to thousands."),
        ("20:24", "An altar; I will record My name."),
        ("24:3-8", "We will do; blood of the covenant on the people."),
        ("28:36-38", "Plate on the forehead; Aaron bears iniquity — crown imagery."),
        ("32:1-35", "A nation's idolatry; Moses stands in the gap."),
        ("34:6-7", "Merciful; forgiving; visiting iniquity of the fathers."),
        ("34:14", "The LORD, whose name is Jealous."),
    ]),
    ("Leviticus", [
        ("4:3, 13-21", "Sin of the priest and of the whole congregation atoned."),
        ("5:5", "He shall confess that he hath sinned."),
        ("16:21-22", "Confess over the scapegoat all the iniquities of the children of Israel."),
        ("17:11", "Life is in the blood; it is the blood that makes atonement."),
        ("18:24-30", "The land vomits nations for their iniquity — a people's record."),
        ("20:5", "I will set My face against that man and his family."),
        ("26:39-45", "Pine away in iniquity of fathers; confess; God remembers the covenant."),
    ]),
    ("Numbers", [
        ("14:18-19", "Visiting iniquity; pardon the iniquity of this people."),
        ("14:31-33", "Your children shall wander; they bear your whoredoms."),
        ("16:23-35", "Korah: separate from the tents of these wicked men; households swallowed."),
        ("25:1-13", "Peor; Phinehas turns wrath; covenant of peace."),
        ("30:3-16", "Vows bind a house; a father/husband may disannul."),
        ("35:33-34", "Blood defiles the land; it cannot be cleansed but by the blood of him that shed it."),
    ]),
    ("Deuteronomy", [
        ("4:9-10", "Teach thy sons and thy sons' sons."),
        ("5:9-10", "Third and fourth; mercy to thousands."),
        ("6:4-9", "These words upon heart; teach them diligently to thy children."),
        ("7:9-10", "Mercy to a thousand generations; repay them that hate Him."),
        ("11:18-21", "That your days and the days of your children may be multiplied."),
        ("21:1-9", "Unknown murder: the elders answer bloodguilt for the land."),
        ("23:2-8", "Generational bars from the congregation — and exceptions of mercy."),
        ("24:16", "Fathers not put to death for children: personal guilt remains, even while other texts name visitation."),
        ("27:14-26", "All the people say Amen to the curses — spoken corporate agreement."),
        ("28:1-68", "Blessings and curses on a people and their fruit, children, and land."),
        ("29:10-21", "Captains, little ones, wives, stranger — all enter the covenant."),
        ("29:14-15", "Not with you only; with him that is not here with us this day."),
        ("30:1-6", "Return; the LORD will circumcise thy heart and the heart of thy seed."),
        ("30:19-20", "Life and death; choose life, thou and thy seed."),
        ("32:7", "Ask thy father, and he will shew thee; thy elders."),
    ]),
    ("Joshua", [
        ("5:2-9", "Circumcision of the generation born in the wilderness."),
        ("7:1-26", "Israel sinned; Achan's house judged for a hidden record."),
        ("24:14-27", "As for me and my house; put away gods; a stone as witness."),
    ]),
    ("Judges", [
        ("2:10-19", "Another generation which knew not the LORD; the cycle of the fathers."),
        ("3:7", "Forgot the LORD and served Baalim."),
        ("6:25-32", "Throw down father's altar of Baal; build the LORD's altar."),
        ("17:6; 21:25", "Every man did that which was right in his own eyes."),
    ]),
    ("Ruth", [
        ("1:16-17", "Thy people shall be my people; thy God my God — a line grafted in."),
        ("4:10-22", "Kinsman-redeemer raises the name of the dead upon his inheritance; genealogy to David."),
    ]),
    ("1 Samuel", [
        ("2:30-36", "Them that honour Me I will honour; judgment on Eli's house."),
        ("3:13-14", "I have told him that I will judge his house for ever."),
        ("7:3-6", "Put away strange gods; we have sinned against the LORD."),
        ("15:22-23", "Rebellion as witchcraft; stubbornness as idolatry."),
        ("16:7", "The LORD looks on the heart."),
        ("24:12, 15", "The LORD judge between me and thee."),
        ("26:23", "The LORD render to every man his righteousness."),
    ]),
    ("2 Samuel", [
        ("7:12-16", "I will set up thy seed; house, kingdom, throne."),
        ("12:10-14", "The sword shall never depart from thine house."),
        ("21:1-14", "Famine for Saul and his bloody house; the record answered."),
        ("24:10-25", "I have sinned; altar on the threshingfloor; plague stayed."),
    ]),
    ("1 Kings", [
        ("2:31-33", "Blood of Joab upon his head and upon his seed."),
        ("8:46-50", "If they sin, bethink themselves, confess; forgive Thy people."),
        ("11:11-13", "For David's sake I will not do it in thy days — a line's mercy."),
        ("15:3", "Walked in all the sins of his father."),
        ("18:21, 30-39", "How long halt; repair the altar; the LORD He is God."),
        ("21:21-29", "I will bring evil upon thy house; because Ahab humbled himself, not in his days."),
    ]),
    ("2 Kings", [
        ("5:27", "The leprosy of Naaman shall cleave unto thee and unto thy seed."),
        ("10:30", "Thy children of the fourth generation shall sit on the throne."),
        ("17:7-23", "They followed the statutes of the heathen and of the kings of Israel."),
        ("21:10-15", "Manasseh: I will bring such evil upon Jerusalem."),
        ("22:8-20", "The book found; wrath because our fathers have not hearkened."),
        ("23:1-3, 25", "Covenant before the LORD; Josiah turned with all his heart."),
        ("24:3-4", "At the commandment of the LORD… for the sins of Manasseh."),
    ]),
    ("1 Chronicles", [
        ("16:15-17", "Be ye mindful of His covenant… to a thousand generations."),
        ("28:8-9", "Keep and seek; if thou forsake Him, He will cast thee off for ever."),
        ("29:18", "O LORD God of Abraham, Isaac, and of Israel, keep this for ever in the imagination of the thoughts of the heart of Thy people."),
    ]),
    ("2 Chronicles", [
        ("6:36-39", "If they pray and confess; forgive Thy people."),
        ("7:14", "If My people… humble, pray, seek, turn; I will hear, forgive, heal."),
        ("19:6-7", "Ye judge not for man, but for the LORD; no iniquity with Him."),
        ("20:12-15", "We have no might; the battle is not yours."),
        ("29:6-10", "Our fathers have trespassed; now it is in mine heart to make a covenant."),
        ("30:6-9", "Turn again; if ye turn, the LORD will return to your children."),
        ("34:21-33", "Great is the wrath because our fathers have not kept the word."),
    ]),
    ("Ezra", [
        ("9:6-15", "O my God, I am ashamed; our iniquities, our fathers; WE."),
        ("10:1-12", "We have trespassed; let us make a covenant; the people answer."),
    ]),
    ("Nehemiah", [
        ("1:4-11", "I and my father's house have sinned; remember the word to Moses."),
        ("8:1-12", "The law read; the people weep and then keep the feast."),
        ("9:1-3", "Separated themselves; confessed their sins and the iniquities of their fathers."),
        ("9:16-38", "Our fathers dealt proudly; Thou art just; we make a sure covenant."),
    ]),
    ("Esther", [
        ("4:14", "If thou holdest thy peace, enlargement from another place; thou and thy father's house."),
        ("8:6", "How can I endure to see the destruction of my kindred?"),
        ("9:27-28", "The Jews ordained it for themselves and for their seed."),
    ]),
    ("Job", [
        ("1:5", "Job sanctified his sons; offered burnt offerings continually."),
        ("1:8-11", "The accuser against a man and all that he has."),
        ("42:7-10", "My servant Job shall pray for you; the LORD turned the captivity."),
    ]),
    ("Psalms", [
        ("7:8-9, 16", "Judge me, O LORD; mischief return upon his own head."),
        ("32:1-5", "Blessed is he whose transgression is forgiven; I acknowledged."),
        ("51:1-17", "Against Thee; wash me; a broken spirit; then sacrifice."),
        ("78:1-8", "We will not hide from their children; a generation that set not their heart aright."),
        ("79:8-9", "Remember not against us former iniquities."),
        ("85:1-7", "Thou hast forgiven the iniquity of Thy people; turn us."),
        ("90:8", "Thou hast set our iniquities before Thee."),
        ("103:17-18", "Mercy from everlasting to everlasting upon them that fear Him, and His righteousness unto children's children."),
        ("106:6-7", "We have sinned with our fathers."),
        ("109:14-15", "Let the iniquity of his fathers be remembered."),
        ("127:3-5", "Children are an heritage of the LORD."),
        ("139:23-24", "Search me; know my thoughts; lead me."),
    ]),
    ("Proverbs", [
        ("3:5-7", "Trust in the LORD; be not wise in thine own eyes."),
        ("4:23", "Keep thy heart with all diligence."),
        ("11:21", "The seed of the righteous shall be delivered."),
        ("13:22", "A good man leaveth an inheritance to his children's children."),
        ("14:26", "In the fear of the LORD is strong confidence; His children shall have a place of refuge."),
        ("16:31", "A crown of glory if found in the way of righteousness."),
        ("20:7", "The just man's children are blessed after him."),
        ("22:6", "Train up a child in the way he should go."),
        ("28:13", "He that covereth his sins shall not prosper."),
    ]),
    ("Ecclesiastes", [
        ("12:13-14", "Fear God and keep His commandments; God shall bring every work into judgment."),
    ]),
    ("Song of Solomon", [
        ("8:6-7", "Love as a seal; jealousy as cruel as the grave — covenant claim vs rival claim."),
    ]),
    ("Isaiah", [
        ("1:2-4", "I have nourished children, and they have rebelled."),
        ("1:18", "Though your sins be as scarlet…"),
        ("6:5-7", "I am a man of unclean lips; a coal from the altar."),
        ("14:21", "Prepare slaughter for his children for the iniquity of their fathers."),
        ("28:14-18", "Covenant with death disannulled; agreement with hell shall not stand."),
        ("43:25-27", "I blot out; put Me in remembrance; thy first father hath sinned."),
        ("44:3-5", "I will pour My spirit upon thy seed."),
        ("49:8-9", "Say to the prisoners, Go forth."),
        ("49:14-26", "Can a woman forget? Even the captives of the mighty shall be taken; I will save thy children."),
        ("53:4-12", "He bare the sin of many; made intercession."),
        ("54:13", "All thy children shall be taught of the LORD."),
        ("58:6, 12", "Loose the bands; raise up the foundations of many generations."),
        ("59:12-21", "Our transgressions; the Redeemer; My spirit and words shall not depart from thy seed."),
        ("61:1-4", "Liberty to the captives; repair the waste cities."),
        ("63:16", "Doubtless Thou art our father, though Abraham be ignorant of us."),
        ("64:6-9", "We are the clay; we are all Thy people."),
    ]),
    ("Jeremiah", [
        ("3:1-14", "Treacherous wife; bill of divorce; return, I am married unto you."),
        ("4:14", "Wash thine heart from wickedness; vain thoughts."),
        ("11:3-10", "Cursed be the man that obeyeth not this covenant… the fathers."),
        ("14:7, 20", "Our backslidings; we acknowledge… the iniquity of our fathers."),
        ("16:10-13", "Wherefore hath the LORD pronounced all this great evil? Because your fathers…"),
        ("17:1", "The sin of Judah is written with a pen of iron… upon the table of their heart."),
        ("18:7-10", "If that nation turn, I will repent of the evil."),
        ("31:29-34", "Fathers have eaten sour grapes; new covenant; I will remember their sin no more."),
        ("32:18-19", "Recompensest the iniquity of the fathers into the bosom of their children."),
        ("35:18-19", "Because ye have obeyed the commandment of your father Jonadab."),
        ("50:20", "The iniquity of Israel shall be sought for, and there shall be none."),
    ]),
    ("Lamentations", [
        ("3:39-41", "Let us search and try our ways, and turn again to the LORD."),
        ("5:7", "Our fathers have sinned, and are not; and we have borne their iniquities."),
        ("5:16", "The crown is fallen from our head: woe unto us, that we have sinned!"),
    ]),
    ("Ezekiel", [
        ("3:17-21", "Watchman: warn, or his blood will I require at thine hand."),
        ("14:3-7", "Idols in their heart; I the LORD will answer him that cometh."),
        ("16:1-63", "Jerusalem's birth, adultery with idols, and remembered covenant."),
        ("18:1-32", "Sour grapes proverb; the soul that sinneth; turn and live."),
        ("20:18-24", "Walk ye not in the statutes of your fathers."),
        ("22:30", "I sought for a man to stand in the gap."),
        ("33:10-16", "If our transgressions be upon us… turn, and live."),
        ("36:24-27", "A new heart and a new spirit."),
        ("37:11-14", "These bones are the whole house of Israel."),
    ]),
    ("Daniel", [
        ("9:3-19", "We have sinned; our fathers; the whole city and people named in one mouth."),
        ("10:12-21", "Princes of Persia and Grecia; Michael — principalities behind nations."),
    ]),
    ("Hosea", [
        ("1:2-11", "Children of whoredoms; Lo-ammi; yet ye are the sons of the living God."),
        ("2:2-23", "She is not My wife; then betrothed in righteousness."),
        ("3:1-5", "Love a woman beloved of her friend, yet an adulteress."),
        ("4:6", "My people are destroyed for lack of knowledge; I will also forget thy children."),
        ("5:4", "They will not frame their doings to turn unto their God."),
        ("14:1-4", "O Israel, return; take away all iniquity."),
    ]),
    ("Joel", [
        ("1:3", "Tell ye your children, and let your children tell their children."),
        ("2:12-18", "Turn ye even to Me with all your heart; the LORD will be jealous for His land."),
        ("2:28-29", "I will pour out My spirit upon all flesh; your sons and your daughters."),
    ]),
    ("Amos", [
        ("3:1-2", "The whole family which I brought up from Egypt; you only have I known."),
        ("5:4-6, 14-15", "Seek Me, and ye shall live."),
        ("7:1-6", "O Lord GOD, forgive, I beseech Thee — intercession for Jacob."),
    ]),
    ("Obadiah", [
        ("10-12", "Violence against thy brother Jacob; thou shouldest not have looked on thy brother."),
    ]),
    ("Jonah", [
        ("3:5-10", "From the king to the least — a city repents as one; God relents."),
        ("4:2", "A gracious God, merciful, slow to anger — the Exodus 34 Name."),
    ]),
    ("Micah", [
        ("6:6-8", "Wherewith shall I come before the LORD? Do justly, love mercy, walk humbly."),
        ("7:18-20", "Who is a God like unto Thee, that pardoneth? Mercy to Abraham, sworn to the fathers."),
    ]),
    ("Nahum", [
        ("1:2-3", "God is jealous; the LORD will take vengeance; slow to anger."),
        ("1:9", "Affliction shall not rise up the second time."),
    ]),
    ("Habakkuk", [
        ("1:13", "Thou art of purer eyes than to behold evil."),
        ("2:4", "The just shall live by his faith."),
        ("3:2", "O LORD, revive Thy work; in wrath remember mercy."),
    ]),
    ("Zephaniah", [
        ("1:4-6", "I will cut off them that turned back from the LORD."),
        ("2:3", "Seek ye the LORD, all ye meek; it may be ye shall be hid."),
        ("3:9-13", "A remnant; they shall not do iniquity."),
    ]),
    ("Haggai", [
        ("1:5-7", "Consider your ways."),
        ("2:12-14", "Holy flesh and uncleanness — transmitted defilement; so is this people."),
    ]),
    ("Zechariah", [
        ("1:2-6", "The LORD hath been sore displeased with your fathers; turn ye unto Me."),
        ("3:1-5", "Satan to accuse Joshua; filthy garments; fair mitre on his head."),
        ("5:1-4", "Flying roll: the curse over the face of the whole earth."),
        ("5:5-11", "Ephah of wickedness carried to its own land."),
        ("12:10", "They shall look upon Me whom they have pierced; a spirit of grace and supplications."),
        ("13:1-2", "A fountain opened; I will cut off the names of the idols."),
    ]),
    ("Malachi", [
        ("1:6", "A son honoureth his father; if I be a father, where is Mine honour?"),
        ("2:10-16", "Have we not all one father? Judah hath dealt treacherously; God hateth putting away."),
        ("3:6-7", "I change not; therefore ye sons of Jacob are not consumed; return unto Me."),
        ("4:5-6", "He shall turn the heart of the fathers to the children, and the heart of the children to their fathers."),
    ]),
    ("Matthew", [
        ("1:1-17", "The genealogy: mercy running through a stained line to Christ."),
        ("3:2, 8-10", "Repent; bring fruit; God is able of these stones to raise up children unto Abraham."),
        ("4:17", "Repent: for the kingdom of heaven is at hand."),
        ("5:23-24", "Leave thy gift before the altar; first be reconciled."),
        ("6:12-15", "Forgive us… as we forgive; if ye forgive not, neither will your Father."),
        ("6:24", "No man can serve two masters."),
        ("12:29", "Bind the strong man; spoil his house."),
        ("12:43-45", "The unclean spirit returns to an empty house with seven worse."),
        ("15:13", "Every plant which My heavenly Father hath not planted shall be rooted up."),
        ("16:19", "Keys; bind and loose on earth and in heaven."),
        ("18:15-20", "If thy brother trespass; two or three agree; gathered in My name."),
        ("18:21-35", "Forgive from the heart; the unforgiving is delivered to tormentors."),
        ("22:37-40", "Love God with all; love neighbour."),
        ("23:29-36", "Ye are the children of them which killed the prophets; all righteous blood upon this generation."),
        ("26:28", "My blood of the new testament, shed for many for the remission of sins."),
        ("27:25", "His blood be on us, and on our children — a spoken bloodline record."),
        ("28:18-20", "All authority; make disciples of all nations."),
    ]),
    ("Mark", [
        ("1:15", "Repent ye, and believe the gospel."),
        ("3:27", "No man can spoil the strong man's house unless he first bind him."),
        ("7:8-13", "Tradition of men making the word of God of none effect — fathers' teaching vs God."),
        ("11:24-26", "When ye stand praying, forgive, if ye have ought against any."),
        ("16:16-17", "He that believeth and is baptized; in My name they shall cast out devils."),
    ]),
    ("Luke", [
        ("1:17", "Turn the hearts of the fathers to the children (Malachi fulfilled)."),
        ("1:50", "His mercy is on them that fear Him from generation to generation."),
        ("1:72-73", "To perform the mercy promised to our fathers."),
        ("3:8", "Begin not to say, We have Abraham to our father."),
        ("3:23-38", "The genealogy to Adam — Round 1's 'all the way back to Adam'."),
        ("4:18-19", "Liberty to the captives; recovering of sight."),
        ("9:23", "Take up his cross daily."),
        ("10:17-20", "Even the devils are subject unto us through Thy name."),
        ("11:4", "Forgive us; for we also forgive."),
        ("11:21-22", "A stronger than he shall come upon him and take his armour."),
        ("13:16", "This woman, a daughter of Abraham, whom Satan hath bound."),
        ("15:11-32", "The son returns; the father runs; the house is the issue."),
        ("17:3-4", "If he repent, forgive him."),
        ("19:8-9", "This day is salvation come to this house."),
        ("23:34", "Father, forgive them; they know not what they do."),
        ("24:47", "Repentance and remission of sins should be preached in His name among all nations."),
    ]),
    ("John", [
        ("1:12-13", "Born not of blood, nor of the will of the flesh, but of God."),
        ("1:29", "Behold the Lamb of God, which taketh away the sin of the world."),
        ("8:32-36", "The truth shall make you free; the servant of sin; the Son makes free indeed."),
        ("8:44", "Ye are of your father the devil — a rival bloodline claim."),
        ("10:10", "The thief comes to steal; I am come that they might have life."),
        ("12:31", "Now shall the prince of this world be cast out."),
        ("14:13-14", "Whatsoever ye shall ask in My name, that will I do."),
        ("16:8-11", "The Spirit will reprove the world of sin, righteousness, and judgment."),
        ("17:15-21", "Keep them from the evil; that they all may be one."),
        ("20:21-23", "As My Father hath sent Me; receive ye the Holy Ghost; remit or retain sins."),
    ]),
    ("Acts", [
        ("2:38-40", "Repent, be baptized for remission; the promise is to you, and to your children, and to all that are afar off; save yourselves from this untoward generation."),
        ("3:19, 25", "Repent, that sins may be blotted out; ye are the children of the covenant."),
        ("7:51", "Ye do always resist the Holy Ghost: as your fathers did, so do ye."),
        ("8:18-24", "Pray God, if perhaps the thought of thine heart may be forgiven thee."),
        ("10:24, 44-48", "Cornelius calls his kinsmen; the Spirit falls on the household."),
        ("11:14", "Who shall tell thee words, whereby thou and all thy house shall be saved."),
        ("16:14-15, 31-34", "Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house."),
        ("19:18-20", "Many that believed came, and confessed, and shewed their deeds."),
        ("26:18", "To turn them from darkness to light, from the power of Satan unto God."),
    ]),
    ("Romans", [
        ("1:21-25", "Vain imaginations; worshiped the creature more than the Creator."),
        ("2:1-6", "Wherein thou judgest another, thou condemnest thyself."),
        ("3:23-25", "All have sinned; propitiation through faith in His blood."),
        ("5:12-21", "By one man sin entered; by the obedience of One shall many be made righteous."),
        ("6:6-23", "Old man crucified; yield yourselves; the wages of sin is death."),
        ("8:1", "No condemnation to them which are in Christ Jesus."),
        ("8:15-17", "Spirit of adoption; we cry, Abba, Father."),
        ("8:26-34", "The Spirit helps; who shall lay any thing to the charge of God's elect?"),
        ("8:38-39", "Neither principalities nor powers shall separate us."),
        ("10:9-13", "Confess with thy mouth; whosoever shall call."),
        ("11:16-24", "If the root be holy, so are the branches; the olive tree of the fathers."),
        ("12:1-2", "Present your bodies a living sacrifice; renew the mind."),
        ("12:19-21", "Vengeance is Mine; overcome evil with good."),
        ("14:12", "Every one of us shall give account of himself to God."),
        ("16:20", "The God of peace shall bruise Satan under your feet shortly."),
    ]),
    ("1 Corinthians", [
        ("5:7", "Christ our passover is sacrificed for us."),
        ("6:9-20", "Such were some of you; ye are washed; body the temple; not one flesh with a harlot."),
        ("7:14", "The unbelieving husband is sanctified by the wife; else were your children unclean."),
        ("10:16-22", "Cup of blessing vs cup of devils; do we provoke the Lord to jealousy?"),
        ("11:25-29", "The new testament in My blood; discern the Lord's body."),
        ("15:21-22, 45-49", "As in Adam all die, even so in Christ shall all be made alive."),
    ]),
    ("2 Corinthians", [
        ("5:17-21", "If any man be in Christ, a new creature; be ye reconciled to God."),
        ("6:14-18", "Be ye separate; I will be a Father unto you, and ye shall be My sons and daughters."),
        ("7:1, 10", "Cleanse from all filthiness of flesh and spirit; godly sorrow worketh repentance."),
        ("10:3-6", "The weapons of our warfare; casting down imaginations; every thought captive."),
        ("11:2-3", "I have espoused you to one husband; as the serpent beguiled Eve."),
    ]),
    ("Galatians", [
        ("3:13-14, 16, 29", "Christ hath redeemed us from the curse; the blessing of Abraham on the Gentiles; to thy seed, which is Christ; if ye be Christ's, then Abraham's seed."),
        ("4:3-9", "In bondage under the elements; how turn ye again to the weak and beggarly?"),
        ("5:1, 19-21", "Stand fast in liberty; works of the flesh."),
        ("6:1-8", "Restore; bear burdens; whatsoever a man soweth."),
    ]),
    ("Ephesians", [
        ("1:7", "Redemption through His blood, the forgiveness of sins."),
        ("2:1-6", "Dead in trespasses; walked according to the prince of the power of the air."),
        ("2:12-19", "Aliens from the commonwealth; now nigh by the blood; one new man."),
        ("3:10", "Principalities and powers in heavenly places made known by the church."),
        ("3:14-15", "The whole family in heaven and earth is named."),
        ("4:17-32", "Futility of mind; put off the old man; forgive as God for Christ's sake hath forgiven you."),
        ("5:8-14", "Have no fellowship with the unfruitful works of darkness."),
        ("5:25-27", "Christ loved the church and gave Himself; a glorious church."),
        ("6:1-4", "Children, obey; fathers, nurture them in the Lord."),
        ("6:10-18", "Put on the whole armour; we wrestle not against flesh and blood."),
    ]),
    ("Philippians", [
        ("2:9-11", "A name which is above every name; every knee should bow."),
        ("3:13-14", "Forgetting those things which are behind; press toward the mark."),
    ]),
    ("Colossians", [
        ("1:13-14", "Delivered from the power of darkness; redemption through His blood."),
        ("2:13-15", "Blotting out the handwriting of ordinances; spoiled principalities."),
        ("3:2-14", "Set your affection above; put off anger; forgive as Christ forgave."),
    ]),
    ("1 Thessalonians", [
        ("5:22-24", "Abstain from all appearance of evil; the God of peace sanctify you wholly."),
    ]),
    ("2 Thessalonians", [
        ("2:7-12", "The mystery of iniquity; strong delusion if they received not the love of the truth."),
        ("3:3", "The Lord is faithful, who shall stablish you, and keep you from evil."),
    ]),
    ("1 Timothy", [
        ("1:18-20", "War a good warfare; holding faith and a good conscience."),
        ("2:1-6", "Prayers for all men; one Mediator; who gave Himself a ransom."),
        ("4:1-2", "Seducing spirits; doctrines of devils; conscience seared."),
        ("5:8, 22", "Provide for his own house; neither be partaker of other men's sins."),
    ]),
    ("2 Timothy", [
        ("1:5", "The unfeigned faith that dwelt first in thy grandmother Lois, and thy mother Eunice."),
        ("2:19-26", "Depart from iniquity; recover themselves out of the snare of the devil."),
        ("3:15", "From a child thou hast known the holy scriptures."),
    ]),
    ("Titus", [
        ("1:15-16", "Unto the pure all things are pure; they deny Him in works."),
        ("2:11-14", "The grace of God; redeem us from all iniquity."),
        ("3:3-7", "We ourselves were sometimes foolish; according to His mercy He saved us."),
    ]),
    ("Philemon", [
        ("10-18", "Receive him as myself; if he hath wronged thee, put that on mine account — representative covering in a household."),
    ]),
    ("Hebrews", [
        ("2:14-15", "Through death He destroyed him that had the power of death, that is, the devil."),
        ("4:12-16", "The word discerns thoughts; come boldly to the throne of grace."),
        ("6:13-20", "God swore by Himself to Abraham; the forerunner within the veil."),
        ("7:9-10, 25", "Levi paid tithes in Abraham; He ever liveth to make intercession."),
        ("8:6-13", "A better covenant; I will be to them a God; their sins I will remember no more."),
        ("9:12-22", "By His own blood; without shedding of blood is no remission."),
        ("10:16-22", "Hearts sprinkled from an evil conscience; boldness by the blood."),
        ("11:4, 7-9, 20-22", "Abel, Noah, Abraham, Isaac, Jacob, Joseph — faith in a line."),
        ("12:1", "We also are compassed about with so great a cloud of witnesses."),
        ("12:16-17", "Esau found no place of repentance, though he sought it carefully with tears."),
        ("12:22-24", "The blood of sprinkling, that speaketh better things than that of Abel."),
        ("13:8, 10-15", "Jesus Christ the same; we have an altar; the sacrifice of praise."),
    ]),
    ("James", [
        ("1:14-15", "Lust conceives; sin; death."),
        ("3:14-16", "Bitter envying; this wisdom is earthly, sensual, devilish."),
        ("4:4-8", "Ye adulterers; submit; resist the devil; draw nigh to God."),
        ("5:16", "Confess your faults one to another, and pray one for another."),
    ]),
    ("1 Peter", [
        ("1:18-19", "Not redeemed with corruptible things… but with the precious blood of Christ."),
        ("2:9-11, 24", "A chosen generation; a royal priesthood; by whose stripes ye were healed."),
        ("3:18-22", "Christ suffered; baptism; the answer of a good conscience."),
        ("5:8-10", "Your adversary the devil; resist; the God of all grace will stablish you."),
    ]),
    ("2 Peter", [
        ("1:4", "Partakers of the divine nature, having escaped the corruption that is in the world through lust."),
        ("2:19", "Of whom a man is overcome, of the same is he brought in bondage."),
        ("3:9", "Not willing that any should perish, but that all should come to repentance."),
    ]),
    ("1 John", [
        ("1:7-9", "The blood of Jesus Christ His Son cleanseth us from all sin; if we confess."),
        ("2:1-2", "We have an advocate with the Father, Jesus Christ the righteous."),
        ("3:8", "For this purpose the Son of God was manifested, that He might destroy the works of the devil."),
        ("4:4", "Greater is He that is in you, than he that is in the world."),
        ("5:16-21", "Sin not unto death; keep yourselves from idols."),
    ]),
    ("2 John", [
        ("4", "I rejoiced greatly that I found of thy children walking in truth."),
    ]),
    ("3 John", [
        ("4", "I have no greater joy than to hear that my children walk in truth."),
    ]),
    ("Jude", [
        ("3-4", "Contend for the faith; ungodly men crept in unawares."),
        ("20-25", "Building up yourselves; keep yourselves in the love of God; unto Him that is able to keep you from falling."),
    ]),
    ("Revelation", [
        ("1:5-6", "Unto Him that loved us, and washed us from our sins in His own blood."),
        ("2:7, 11, 17, 26; 3:5, 12, 21", "To him that overcometh — a closed case, a new name, a crown kept."),
        ("3:11", "Hold that fast which thou hast, that no man take thy crown."),
        ("5:9-10", "Thou wast slain, and hast redeemed us to God by Thy blood out of every kindred."),
        ("12:7-11", "The accuser of our brethren is cast down; they overcame him by the blood of the Lamb, and by the word of their testimony."),
        ("13:8", "The Lamb slain from the foundation of the world."),
        ("17:5", "Mystery, Babylon the Great, the Mother of Harlots — a counterfeit mother-line."),
        ("18:4-5", "Come out of her, My people; her sins have reached unto heaven."),
        ("20:12", "The dead were judged out of those things which were written in the books."),
        ("21:7-8, 27", "He that overcometh shall inherit; nothing that defileth shall enter."),
        ("22:3-4", "No more curse; His name in their foreheads."),
        ("22:14-17", "Blessed are they that do His commandments; the Spirit and the bride say, Come."),
    ]),
]
